### ISSUE TITLE
Circuits

### ISSUE THREAD

**Issue by ianitsky** [adeyblue/GTVolTools#3]
GTVOLTools can extract varius types of files and cars. But have a way of extract circuits from GT1&2?

Thanks

**Comment by adeyblue** [comment]
In GT2 & 3, the circuit files are part of the VOL so GTVolTool(Gui) will extract them like all the other files in the VOL.
If you want to actually do anything with them like view the models or change anything, then no, you can't do anything like that with these tools, and I've no intention of adding anything like that,

Deending on what you want to do, you might have better luck asking in the GT2 forum on GTPlanet. That's where the current perople who are seriously into Gran Turismo modding are, and if anybody has tools to view or modify circuits, they will.
https://www.gtplanet.net/forum/board/gran-turismo-2.11/
